repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    -   id: isort
        args: ["--profile", "black", "--extend-skip", "examples"]
        name: Running isort in all files.

  - repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
    -   id: black
        name: Running black in all files.
